### ISSUE TITLE
Regression: Various graphical defects

### ISSUE THREAD

**Issue by joshqou** [icedman/dash2dock-lite#115] opened 2024-04-03 05:17 UTC
Updated from b81f786ee91f5bd77cbebbbdb5b5343d6eadc609 to ebc16577a39e3e6a8be0fd57a1b6e7839af51fdf and I'm getting some weird rendering artifacts. Primarily overly pixelated icons, icons losing their bottom padding, and render tearing

![image](https://github.com/icedman/dash2dock-lite/assets/97894002/46f829d8-0399-4c98-86f9-26c582b295b0)

![image](https://github.com/icedman/dash2dock-lite/assets/97894002/4e57c412-9be3-4fc4-8737-9a3b2b25a9bf)

There was also a very odd bug where the icon's containers would be stretched upwards (visible somewhat in the image) for small icon sizes with shrink icons enabled, however I can't seem to reproduce that after resetting extension settings.

**Comment by icedman** [comment] 2024-04-03 06:44
I saw this once or twice. But could not reproduce anymore.

I reverted a change which possibly caused this. You try the next commit. And play around the icon sizes and icon quality. To see what might cause this.

**Comment by FrancescoCaracciolo** [comment] 2024-04-03 18:29
I had the same issue, installing from current main branch fixed it

**Comment by icedman** [comment] 2024-04-04 00:29
> Nevermind, I have this problem again ![immagine](https://private-user-images.githubusercontent.com/67018178/319311334-b84070fd-ed4a-47df-aaa9-8bdad0fb53e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxOTA4MDgsIm5iZiI6MTcxMjE5MDUwOCwicGF0aCI6Ii82NzAxODE3OC8zMTkzMTEzMzQtYjg0MDcwZmQtZWQ0YS00N2RmLWFhYTktOGJkYWQwZmI1M2UyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDAwMjgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhOTdhNmI2ODg1ZjYwMTJlYjcyMDc1MjFhZDNiMGNmOGE3OTdkZDRjNmQ0NmYyZmRhM2Q5MmFmMjU5ZGY3YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bQSauJVYRsvGqv2bLp8e0S8JOHEuVc1KdAtuJnxCKVY)

Please also try resetting the settings.

**Comment by icedman** [comment] 2024-04-04 08:54
I reverted another previous change. The icon size is now again constantly recalculated while in animation. This uses a little bit more CPU but seems to fix the pixelated issue.

**Comment by FrancescoCaracciolo** [comment] 2024-04-06 10:11
![image](https://github.com/icedman/dash2dock-lite/assets/67018178/ccfa28bd-7590-47d0-99c3-51bd3f71f973)
Default settings, dash2dock extension enabled, main branch

**Comment by icedman** [comment] 2024-04-06 10:29
Could you check the logs if an error occurred somewhere

**Comment by FrancescoCaracciolo** [comment] 2024-04-06 10:34
> Could you check the logs if an error occurred somewhere

How do I check the logs?



> Oh.. main branch.. I have not pushed to the main branch yet.. will do after go through my checklist

Do I need to test the development branch?

**Comment by icedman** [comment] 2024-04-06 10:42
```sh
journalctl /usr/bin/gnome-shell -f -o cat
```
Watch the log while running the extension. And look for errors the moment the icons become pixelated.

I haven't seen pixelation error since I reverted some changes. But it is in the development branch yet.
I would really help if you could check it out. So I could close the issue.

**Comment by icedman** [comment] 2024-04-06 10:46
Also, are you using PNG icons. Try SVG icons see if there is any difference.

**Comment by FrancescoCaracciolo** [comment] 2024-04-06 11:11
Still on main branch
I switched to default adwaita icons before (default icon quality, no log)
Only the gnome-extensions icon seems pixelated for some reason, but it's good looking overall 
![image](https://github.com/icedman/dash2dock-lite/assets/67018178/65cbc326-1334-4890-b644-39be2537dce0)
While the extension is enabled, I switched icon pack back to tela icon pack it was way more pixelated
![image](https://github.com/icedman/dash2dock-lite/assets/67018178/ebe7bc66-398f-45ec-80a7-033f07082ef7)
And then switching back to adwaita (they are now way more pixelated):
![image](https://github.com/icedman/dash2dock-lite/assets/67018178/44af0a0a-c435-42ad-9f39-d9685662a4be)
All of this with default icon quality (the behavoir is pretty similar even with a different icon quality)
Here are the log white I did all of this: https://pastebin.com/3h1BRDbd

**Comment by icedman** [comment] 2024-04-06 11:45
Thank you. This is helpful.

**Comment by icedman** [comment] 2024-04-06 12:02
I merged the development branch to main. This still has a few issues. - But not of them are nastier than that pixelation bug.

**Comment by icedman** [comment] 2024-04-07 22:56
Did a coding binge last night to fix these pixelated icons bug. Please checkout the development branch.

**Comment by fekzol** [comment] 2024-04-09 17:30
With disabled animations there are some annoying black backgrounds behind the icons. How can i get rid of them? Had not found any color setting for that.
![Screenshot from 2024-04-09 19-26-53](https://github.com/icedman/dash2dock-lite/assets/50592726/6f0d7ec2-2de3-4f32-9e2b-e30cc24bdedf)

**Comment by icedman** [comment] 2024-04-10 01:24
Looks like a css style from your OS. This will have to be overriden by the extension. I will include in the next release.

**Closed** 2024-05-01 14:21 UTC
