### ISSUE TITLE
Dash and Dock are overlapping each other when auto-hide enabled

### ISSUE THREAD

**Issue by Thor-x86** [icedman/dash2dock-lite#113] opened 2024-04-02 13:15 UTC
Dash and Dock are overlapping as screenshot below.

![Screenshot from 2024-04-02 20-07-08](https://github.com/icedman/dash2dock-lite/assets/30412448/c95277b1-346e-4962-8b97-8884bcf4d80e)

The issue is exist after enabling:
- Autohide Icons
- Dodge Only

My system details:
- Dash2Dock Animated v54
- Gnome v46.0
- Linux Kernel v6.8.2-arch2-1
- EndeavourOS Linux x86_64
- AMD Ryzen 7 3700U (with GPU Radeon Vega 10 Picasso)

**Comment by icedman** [comment] 2024-04-04 12:55
I could not reproduce in any of these:

* Arch Linux (Gnome 45.5)
* Ubuntu 23 (Gnome 45.0)
* Debian 12 (Gnome 43.9)
* Manjaro Linux (Gnome 45.3)
* Fedora 39 (Gnome 45.0)
* Fedora 40 Beta (Gnome 46.0)
* Opensuse Tumbleweed (Gnome 46.0)

Unfortunately I've run out of disk space for EndevourOS. Please check the log for any exceptions.  In any case, I've pushed a possible fix.

**Comment by mtoniott** [comment] 2024-04-08 09:16
Same problem on ArchLinux with Gnome 46.0

**Comment by Kartikeyvarshney** [comment] 2024-04-08 09:42
you can solve this problem by disabling the ubuntu dock in extension manager , by doing so you are disable the default dock because default dock is disable it will not going to overlap with animated one.
![Screenshot from 2024-04-08 14-50-14](https://github.com/icedman/dash2dock-lite/assets/105634736/4c538eb0-9d03-4c5e-b80e-8751a112db50)

**Comment by Thor-x86** [comment] 2024-04-08 12:22
> you can solve this problem by disabling the ubuntu dock in extension manager

The Ubuntu Dock is not installed, so I don't think that's the problem

> Same problem on ArchLinux with Gnome 46.0

Thanks for the information, consider reproduce on Gnome 46.0 with Arch Linux based distro?

**Comment by icedman** [comment] 2024-04-08 12:33
I still haven't reproduced this. My Arch is still at Gnome 46 at the moment. 
Could you check the logs at startup. or after suspend. run ```journalctl ```

**Comment by Lija321** [comment] 2024-04-09 18:58
I also have the problem


# System Details Report
## Software Information:
- **Firmware Version:**                            F3
- **OS Name:**                                     Ubuntu 23.10
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.2
- **Windowing System:**                            X11
- **Kernel Version:**                              Linux 6.5.0-27-generic

**Comment by timurtuty** [comment] 2024-04-19 17:29
It seems that this problem occures when changing the opacity of the previous panel. For example, when you interact with the application window from the observation area (Win or Super). 

Well, that's how it happens to me.

_I dont know what to call it. observation area?_

**Comment by timurtuty** [comment] 2024-04-20 18:15
To solve this problem, we need to replace
```js
Main.overview.dash.opacity = 0;
```
with
```js
Main.overview.dash.hide();
Main.overview.dash.set_height(1);
```
and to replace
```js
Main.overview.dash.opacity = 255;
```
with
```js
Main.overview.dash.show();
Main.overview.dash.set_height(-1);
```
in [extension.js](https://github.com/icedman/dash2dock-lite/blob/main/extension.js)

**Comment by Thor-x86** [comment] 2024-04-22 20:57
Sorry for taking too long, there is nothing in the logs

```
$ sudo journalctl -xefu gdm
Apr 21 14:48:40 HP-Envy systemd[1]: Starting GNOME Display Manager...
░░ Subject: A start job for unit gdm.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit gdm.service has begun execution.
░░ 
░░ The job identifier is 312.
Apr 21 14:48:41 HP-Envy systemd[1]: Started GNOME Display Manager.
░░ Subject: A start job for unit gdm.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit gdm.service has finished successfully.
░░ 
░░ The job identifier is 312.
Apr 21 14:48:41 HP-Envy gdm-autologin][966]: pam_unix(gdm-autologin:session): session opened for user athaariq(uid=1000) by athaariq(uid=0)
Apr 21 14:48:41 HP-Envy gdm-autologin][966]: gkr-pam: couldn't unlock the login keyring.
```

> It seems that this problem occures when changing the opacity of the previous panel. For example, when you interact with the application window from the observation area (Win or Super).

This happened on me too. Exactly when I dragged a window at the observation area.

**Comment by icedman** [comment] 2024-04-23 03:51
I was able to recreate the problem, thanks to @timurtuty  . I also pushed a fix already.

**Closed** 2024-05-01 14:23 UTC
